name: Deploy to Oracle Instance

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Load code from GitHub repository
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Copy application-prod.yml
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application-prod.yml

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "credential.json"
          json: ${{ secrets.GOOGLE_CREDENTIAL_JSON }}
          dir: 'src/main/resources/'

      - name: Copy gradle.properties
        run: |
          echo "${{ secrets.GRADLE_PROPERTIES }}" > gradle.properties

      - name: Cache Gradle caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ github.job}}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-${{ github.job }}

      - name: Cache Jib layers
        uses: actions/cache@v3
        with:
          path: |
            ./build/jib-cache
            ./build/jib-image.digest
            ./build/jib-image.id
            ./build/jib-image.json
          key: ${{ runner.os }}-jib-${{ github.job }}-${{ hashFiles('**/build.gradle') }}
          restore-keys: ${{ runner.os }}-jib-${{ github.job }}

      - name: Build and push image with Jib
        run: ./gradlew jib

      - name: SSH into Oracle VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORACLE_VM_IP }}
          username: ${{ secrets.ORACLE_VM_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd ~/GDGoc-TUK-Official-Backend/

            sudo git pull
            
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            
            sudo docker compose -f docker-compose.prod.yml down || true
            
            sudo docker compose -f docker-compose.prod.yml pull
            
            sudo docker compose -f docker-compose.prod.yml up -d
            
            sudo docker image prune -f
