name: Deploy to GCP Compute Instance

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Load code from GitHub repository
        uses: actions/checkout@v4

      - name: Install JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21  

      - name: Copy application-prod.yml
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application-prod.yml

      - name: SSH into GCP VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd ~/GDGoc-TUK-Official-Backend/

            sudo git pull
            
            echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
            
            sudo docker compose -f docker-compose.prod.yml down || true
            
            sudo docker compose -f docker-compose.prod.yml pull
            
            sudo docker compose -f docker-compose.prod.yml up -d
            
            sudo docker image prune -f
